project:
  owner: quickstart-eng@amazon.com
  name: quickstart-qumulo-cloud-q
  package_lambda: false
  regions:
  - us-east-1
tests:
  quickstart-qumulo-cloud-q:
    parameters:
      AvailabilityZone: $[taskcat_getaz_1]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      KeyPair: $[taskcat_getkeypair]
      QPublicMgmt: "YES"
      QDiskConfig: "600GiB-AF"
      QClusterAdminPwd: P!$[taskcat_genpass_12A]
      SideCarAZ: $[taskcat_getaz_1]
      SideCarPassword: P!$[taskcat_genpass_12A]
    regions:
    - us-east-1
    template: templates/qs-cloudq-main-new-vpc.template.yaml
