// Edit this placeholder text to accurately describe your architecture.

This Quick Start provides three deployment options:

* *Deploy {partner-product-short-name} into a new VPC*. This option builds a new AWS environment consisting of the VPC, subnets, NAT gateway, security groups, and other infrastructure components. It then deploys {partner-product-short-name} into this new VPC with all the parameters of the advanced template.
* *Deploy {partner-product-short-name} into an existing VPC - Advanced*. This option provisions {partner-product-short-name} in your existing AWS infrastructure with all advanced parameters configurable.
* *Deploy {partner-product-short-name} into an existing VPC - Standard*. This option provisions {partner-product-short-name} in your existing AWS infrastructure with a minimal set of parameters.

The Quick Start provides separate templates for these options. It also lets you configure Classless Inter-Domain Routing (CIDR) blocks, instance types, and {partner-product-short-name} settings, as discussed later in this guide.

==== Choose the template that matches the deployment requirements
The table below compares the deployment, customization, and optional parameters between the three templates.

|===

// space for headers
||Existing VPC - Standard |Exiting VPC - Advanced |New VPC
|Deploy from Quick Start Bucket |✓ |✓ |✓
|Deploy from your own Bucket | |✓ |✓ 
|Deploy Any Qumulo Marketplace Offering |✓ |✓ |✓ 
|Deploy with a Qumulo Custom AMI-ID | |✓ |✓ 
|Deploy in a Local Zone | |✓ |✓ 
|Deploy on Outpost | |✓ | 
|Deploy in a VPC with no Internet Access | |✓ | 
|Customize Qumulo Admin Password |✓ |✓ |✓ 
|Customize Qumulo EC2 Instance Type |✓ |✓ |✓ 
|Customize Qumulo EC2 Instance Count |✓ |✓ |✓ 
|Customize Termination Protection |✓ |✓ |✓ 
|Customize Qumulo Name | |✓ |✓ 
|Customize Qumulo Software Version | |✓ |✓ 
|Customize Qumulo Sidecar deployment | |✓ |✓ 
|Customize Qumulo # of Floating IPs | |✓ |✓ 
|Optional: Add SNS Topics for Instance an Volume recovery | |✓ |✓ 
|Optional: Add Route 53 PHZ DNS for Floating IPs | |✓ |✓ 
|Optional: Add CIDRs to Qumulo Security Group | |✓ |✓ 
|Optional: Add Qumulo Public Management | |✓ |✓ 
|Optional: Add Qumulo Public Replication Port | |✓ |✓ 
|Optional: Enable CloudWatch Audit Log Messages | |✓ |✓ 
|Optional: Apply CMK for EBS Encryption | |✓ |✓ 
|Optional: Set IAM Permissions Boundary | |✓ |✓ 
|Optional: Specify Environment type | |✓ |✓ 
|===

