=== Confirm your AWS account configuration

. Sign in to your AWS account at https://aws.amazon.com with an IAM user or role that has the necessary permissions. For details, see link:#_planning_the_deployment[Planning the deployment] earlier in this guide.
. Make sure that your AWS account is configured correctly, as discussed in the link:#_technical_requirements[Technical requirements] section.

=== Subscribe to a Qumulo Marketplace AMI

. Go to the https://aws.amazon.com/marketplace[AWS Marketplace^].

. In the search bar, enter `Qumulo`. 

. Choose the offering with the appropriate capacity for your configuration and deployment Region.

. Choose *Continue to Subscribe* on the upper right. The subscription processes within a few minutes.

. If you have a private offer, accept the offer by clicking the link you receive in an email. For example, the https://aws.amazon.com/marketplace/pp/prodview-jp4qun3yw5hn4[Qumulo Customizable File Storage Node^] offering (unless you choose 320 TiB per EC2 instance) requires a private offer.

=== Launch the Quick Start
WARNING: If you're deploying {partner-product-short-name} into an existing VPC, ensure that your VPC has both a private and public subnet. This Quick Start doesn't support https://docs.aws.amazon.com/vpc/latest/userguide/vpc-sharing.html[shared subnets^]. These subnets require https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html[NAT gateways^] in their route tables to allow the instances to download packages and software without exposing them to the internet. Also ensure that the domain name option in the Dynamic Host Configuration Protocol (DHCP) options is configured as explained in http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_DHCP_Options.html[DHCP options sets^]. You provide your VPC settings when you launch the Quick Start.

Each deployment takes about {deployment_time} to complete.

. Sign in to your AWS account, and choose one of the following options to launch the AWS CloudFormation template for {partner-product-short-name}. For help with choosing an option, see link:#_deployment_options[Deployment options] earlier in this guide.
+
[cols="3,1"]
|===
^|https://fwd.aws/395mW?[Deploy into a new VPC with advanced parameters^]
^|https://fwd.aws/mA9Nj?[View template^]

^|https://fwd.aws/REjKv?[Deploy into an existing VPC with advanced parameters^]
^|https://fwd.aws/8PwWN?[View template^]

^|https://fwd.aws/6bQmK?[Deploy into an existing VPC with standard parameters^]
^|https://fwd.aws/yEYgV?[View template^]
|===

. Check the AWS Region that's displayed in the upper-right corner of the navigation bar, and change it if necessary. This Region is where you build the network infrastructure. The template is launched in the {default_deployment_region} Region by default. For more information, see link:#_supported_aws_regions[Supported AWS Regions] earlier in this guide.
. On the *Create stack* page, keep the default setting for the template URL, and then choose *Next*.
. On the *Specify stack details* page, change the stack name if needed. Review the parameters for the template. Provide values for the parameters that require input. For all other parameters, review the default settings and customize them as necessary. When you finish reviewing and customizing the parameters, choose *Next*.