==== Allow Qumulo public access if you use AWS Direct Connect

If you use https://aws.amazon.com/directconnect/[AWS Direct Connect^] to connect between an on-premises environment and your AWS VPC, and if you restrict public access to specific URLs with a corporate firewall, ensure that your firewall allows access to the following Qumulo public URLs. While these URLs' public IP addresses are static, they may occasionally change. So, where possible, allow access to the URL. Otherwise, if you must, allow access to the IP address resolved.

[cols="1,3"]
|===
|URL |Description

// Space needed to maintain table headers
|https://trends.qumulo.com | Pulls code for software upgrades during provisioning. Customers may also use this URL for historical statistics for their cluster.
|https://missionq.qumulo.com | Delivers statistics to Qumulo's remote monitoring service, which is included in your Qumulo subscription.
|https://ep1.qumulo.com | (Disabled by default) The cluster uses this URL if you enable remote VPN support for Qumulo Customer Success.
|https://monitor.qumulo.com |Also uses remote VPN support to deliver logs when collaborating with Qumulo Customer Success.
|===