AWSTemplateFormatVersion: "2010-09-09"

# MIT License
#
# Copyright (c) 2021 Qumulo, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal 
# in the Software without restriction, including without limitation the rights 
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell 
# copies of the Software, and to permit persons to whom the Software is 
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all 
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
# SOFTWARE.

Description: This is the main template to spin up a Basic Qumulo Cluster in an existing VPC with minimal options.  It calls cloudq.cft.yaml to instantiate the infrastructure. (qs-1s6n2i6a8)

Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - W9006
        - W9901
  QuickStartDocumentation:
    EntrypointName: 'Parameters for deploying into a new VPC'
    Order: '1'
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: AWS Template Configuration - Cloud Q Quick Start Existing VPC - Standard v3.7
        Parameters:
          - KeyPair

      - Label: 
          default: AWS Network Configuration
        Parameters:
          - VPCId
          - QSgCidr1        
          - PrivateSubnetID                   

      - Label:
          default: Qumulo File Data Platform Configuration
        Parameters:
          - QMarketPlaceType
          - QInstanceType
          - QNodeCount
          - QDiskConfig
          - QClusterAdminPwd
          - TermProtection

      - Label:
          default: Qumulo EBS Monitoring/Replacement & CloudWatch Metrics Configuration
        Parameters:
          - SideCarVersion                    

    ParameterLabels:
      KeyPair:
        default: "AWS Key-Pair Name"
      VPCId:
        default: "AWS VPC ID"
      QSgCidr1:
        default: "Qumulo Security Group CIDR"
      PrivateSubnetID:
        default: "AWS VPC Private Subnet ID"
      QClusterAdminPwd:
        default: "Qumulo Cluster Admin Password"
      QInstanceType:
        default: "Qumulo EC2 Instance Type"
      QNodeCount: 
        default: "Total Number of Qumulo EC2 Instances"
      QDiskConfig:
        default: "EBS Volume Configuration per EC2 Instance"
      QMarketPlaceType:
        default: "Qumulo AWS Marketplace Offering Accepted"
      TermProtection:
        default: "Enable Termination Protection"  
      SideCarVersion:
        default: "Qumulo Sidecar Software Version "            

Parameters:

  KeyPair:
    Description: Name of an existing EC2 Key Pair to enable authentication to instances
    Type: AWS::EC2::KeyPair::KeyName
    Default: mykeypair

  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: AWS VPC ID.

  QSgCidr1:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(3[0-2]|[1-2][0-9]|[0-9]))$"
    Description: An IPv4 CIDR block for specifying the generated security group's allowed addresses for inbound traffic. Typically set to the VPC CIDR.
    Type: String
    Default: "10.0.0.0/16"

  PrivateSubnetID:
    Type: AWS::EC2::Subnet::Id
    Description: AWS Private Subnet in the VPC.

  QInstanceType:
    Description: EC2 instance type for Qumulo nodes.
    AllowedValues:
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.8xlarge
      - m5.12xlarge
      - m5.16xlarge
      - m5.24xlarge
      - c5n.4xlarge
      - c5n.9xlarge
      - c5n.18xlarge
    Type: String
    Default: m5.2xlarge

  QNodeCount:
    Description: "Total number of EC2 instances, or Qumulo Nodes, in the Qumulo Cluster: (4-10).  NOTE: This field may be used to add nodes with a CloudFormation Stack Update after initial provisioning."
    AllowedValues:
      - Select for Custom Offering OR Expanding Cluster
      - "4"
      - "5"
      - "6"
      - "7"
      - "8"
      - "9"
      - "10"
      - "11"
      - "12"
      - "13"
      - "14"
      - "15"
      - "16"
      - "17"
      - "18"
      - "19"
      - "20"            
    Type: String
    Default: Select for Custom Offering OR Expanding Cluster

  QDiskConfig:
    Description: "Choose the EBS Volume configuration and type for the Qumulo EC2 instances: AF= SSD, Hybrid st1= SSD+HDD st1, Hybrid sc1= SSD+HDD sc1. NOTE: This must match the EBS capacity and type of the Customizable Private Offer."
    AllowedValues:
      - Select for Custom Offering
      - 600GiB-AF
      - 1TB-AF
      - 5TB-AF
      - 8TiB-AF
      - 13TiB-AF
      - 20TiB-AF
      - 30TB-AF
      - 35TiB-AF
      - 55TiB-AF
      - 5TB-Hybrid-st1
      - 8TiB-Hybrid-st1
      - 13TiB-Hybrid-st1
      - 20TB-Hybrid-st1
      - 35TiB-Hybrid-st1
      - 55TiB-Hybrid-st1
      - 90TiB-Hybrid-st1
      - 160TiB-Hybrid-st1
      - 256TiB-Hybrid-st1
      - 320TiB-Hybrid-st1
      - 8TiB-Hybrid-sc1
      - 13TiB-Hybrid-sc1
      - 20TB-Hybrid-sc1
      - 35TiB-Hybrid-sc1
      - 55TiB-Hybrid-sc1
      - 90TiB-Hybrid-sc1
      - 160TiB-Hybrid-sc1
      - 256TiB-Hybrid-sc1
      - 320TiB-Hybrid-sc1
    Type: String
    Default: Select for Custom Offering

  QMarketPlaceType:
    Description: Select the Qumulo Cluster usable capacity per the accpeted AWS Marketplace offering.  Customizable offerings typically leverage a Private Offer via AWS Marketplace and can be used to deploy 1TB to 6PB with this template.
    AllowedValues:
      - 1TB-Usable-All-Flash
      - 12TB-Usable-Hybrid-st1
      - 96TB-Usable-Hybrid-st1
      - 103TB-Usable-All-Flash
      - 270TB-Usable-Hybrid-st1
      - 809TB-Usable-Hybrid-st1
      - Custom-1TB-6PB
    Type: String
    Default: 1TB-Usable-All-Flash

  QClusterAdminPwd:
    AllowedPattern: "^(?=.*[a-z])(?=.*[A-Z])(?=.*[@$!%*?&\\-_])[A-Za-z\\d@$!%*?&\\-_]{8,}$"
    Description: "Minumum 8 characters and must include one each of: uppercase, lowercase, and a special character."
    MaxLength: 128
    MinLength: 8
    Type: String
    NoEcho: "true"

  TermProtection:
    Description: Enable Termination Protection for EC2 instances and the CloudFormation stack
    AllowedValues:
      - "YES"
      - "NO"
    Type: String
    Default: "YES"    

  SideCarVersion:
    Description: "Keep default value for new deployments.  NOTE: This field may be used to upgrade the SideCar software version 
                  with a CloudFormation Stack Update after upgrading the cluster via the Web UI or REST API."
    MaxLength: 11
    MinLength: 5
    Type: String
    Default: "4.2.5"

Rules:
  CustomRule:
    RuleCondition: !Equals [!Ref QMarketPlaceType, "Custom-1TB-6PB"]
    Assertions:
      - Assert: !Not [!Equals [!Ref QNodeCount, "Select for Custom Offering OR Expanding Cluster"]]
        AssertDescription: "A Custom Marketplace Offering requires the EC2 Instance Count to be selected. "
      - Assert: !Not [!Equals [!Ref QDiskConfig, "Select for Custom Offering"]]
        AssertDescription: "A Custom Marketplace Offering requires the EBS Volume Configuration to be selected. "  

Resources:

  CloudQStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        QSS3BucketName: "dackss3-dev"
        QSS3KeyPrefix: "quickstart-qumulo-cloud-q/"
        QSS3BucketRegion: "us-west-2"
        KeyPair: !Ref KeyPair
        EnvType: "dev"
        VPCId: !Ref VPCId
        QSgCidr1: !Ref QSgCidr1
        QSgCidr2: ""       
        QSgCidr3: ""   
        QSgCidr4: ""          
        PrivateSubnetID: !Ref PrivateSubnetID
        QClusterLocalZone: "NO"
        SideCarPrivateSubnetID: !Ref PrivateSubnetID
        QPublicMgmt: "NO"
        QPublicRepl: "NO"
        PublicSubnetID: !Ref PrivateSubnetID
        DomainName: ""
        QDr: "NO"
        QFloatRecordName: ""
        QMarketPlaceType: !Ref QMarketPlaceType
        QAmiID: "Only for Specified AMI-ID Offering"
        QAmiVer: "4.2.0"
        QInstanceType: !Ref QInstanceType
        QNodeCount: !Ref QNodeCount
        QDiskConfig: !Ref QDiskConfig
        QFloatingIP: "3"
        QClusterVersion: "4.2.5"
        QClusterName: "Cloud-Q"
        QClusterAdminPwd: !Ref QClusterAdminPwd
        VolumesEncryptionKey: ""
        QPermissionsBoundary: ""       
        QInstanceRecoveryTopic: ""
        QAuditLog: "NO"
        TermProtection: !Ref TermProtection
        SideCarProv: "YES"
        SideCarUsername: "SideCarUser"
        SideCarPassword: !Ref QClusterAdminPwd
        SideCarVersion: !Ref SideCarVersion
        SideCarSNSTopic: ""
      TemplateURL: !Sub "https://dackss3-dev.s3.${AWS::Region}.${AWS::URLSuffix}/quickstart-qumulo-cloud-q/templates/cfn/cloudq.cft.yaml"

Outputs:

  QumuloPrivateIP:
    Description: Private IP for Qumulo Cluster Management
    Value: !GetAtt CloudQStack.Outputs.QumuloPrivateIP
  QumuloKnowledgeBase:
    Description: Qumulo Knowledge Base
    Value: !GetAtt CloudQStack.Outputs.QumuloKnowledgeBase
    



